name: Affect
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - empath
  - gensim
  - nltk
  - spacy
  - scikit-learn
  - pyyaml  
  - emoji
  - pytorch>=1.13  # Add PyTorch to ensure compatibility with the transformers library (was 1.12.1, changing to use MPS for faster roberta model training)
  - transformers=4.17.0  # This will attempt to get the latest version available on conda channels
  - matplotlib
  - pip
  - pip:
    - contractions
    - nrclex
    - tensorflow-hub
    - pyspellchecker
    - translate
    - googletrans
    - sentence_transformers





